spring.application.name=capex-backend

spring.datasource.url=jdbc:h2:file:/workspace/tmp/capex;AUTO_SERVER=TRUE
spring.datasource.username=capex
spring.datasource.password=capex

security.jwt.secret = MySecretThatNeedsToBeLongForItToWork
# 600 seconds = 10 minutes
security.jwt.access-token-expiration-seconds = 600
# 86400 seconds = 24 hours
security.jwt.refresh-token-expiration-seconds = 86400